name: ManhuntPlugin
version: 0.1.3
author: LeoPiGuy
main: com.leopiguy.manhuntplugin.ManhuntPlugin
api-version: 1.15
commands:
  manhunt:
    description: Manhunt command!
    usage: /manhunt <init|add>